# Generated by Django 2.2.3 on 2019-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=30)),
                ('fro', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
