# Generated by Django 2.2.3 on 2019-07-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='fro',
            new_name='sender',
        ),
    ]
